### ISSUE TITLE
Combustion setup eats redstone.

### ISSUE THREAD

**Issue by Runisco** [Bartz24/SkyResources#126]
Quick dropper
Combustion collector
smart combustion controller
Manyullyn Casing with Electrum Combustion Heater fed with RF.

It produces redstone fine with gunpowder and blaze powder.

However, when redstone is dropped using the quick dropper, the redstone dissapears, and never drops into the chamber. No recipe uses redstone only, and nothing goes into the collector, meaning glowstone dust cannot be made with the controller, dropper & collector.

**Comment by eddoww** [comment]
Yep, and by doing so it also makes it non-functional until you move it.

**Comment by Bartz24** [comment]
I can't reproduce this.
Are you on a server?
If you can, send screenshots of the combustion multiblock and the filter in the smart controller

**Comment by eddoww** [comment]
Yep on a server, I'll try and make some screenshots.

**Comment by pinto-omer** [comment]
I'm also experiencing this problem, using version 2.3.0 of the mod, using different casing and heater (refined obsidian + enderium). I'm playing on a single player world that's opened to LAN (so localized server). Attached are the screenshots you previously requested
![2018-04-21_11 45 27](https://user-images.githubusercontent.com/2328915/39082311-e45f908e-4559-11e8-886a-09706bb2dba3.png)
![2018-04-21_11 45 39](https://user-images.githubusercontent.com/2328915/39082312-e47e2ddc-4559-11e8-846c-5b56d767f8ea.png)

**Comment by thelapisfox** [comment]
This problem has also just reared its ugly head on me. I have the same setup and I am no longer able to make glowstone dust due to this. The only difference is I am using Refined Storage to automate the setup. It works fine with making redstone and blaze powder, but glowstone is not working as the redstone vanishes the moment it hits the quick dropper. I have verified it is not being pulled out back into the system, it just vanishes. I have ended up losing 6 stacks of redstone testing this. This occurs in SSP, both open LAN and closed. As for the combustion heater. I have an end stone casing with an Iron heater.

I am playing the Modern Skyblock 3 3.3.1.2 modpack that has 2.3.0 version of Sky Resources 2. 


[modlist.txt](https://github.com/Bartz24/SkyResources/files/1966698/modlist.txt)

Edit: I made a video to show what is going on https://youtu.be/vT760Uq5rBU

Edit 2: I replaced the Quick Dropper with an Automatic Precision Dropper from Actually Additions and the redstone does not disappear, thereby allowing the creation of glowstone. Based on this, the issue is probably with the Quick Dropper. ~~However, after further testing, this seems to not work as well since it drops items one at a time, when trying to make redstone, regardless of the priority you have set within the Smart Combustion Controller, it will always make blaze powder, even if it places the blaze powder first, it will still make more blaze powder.~~ (Scratch that. Seems it doesn't matter what type of dropper you use, if you have the blaze powder within the smart controller, it will ALWAYS give that priority over anything else).

**Comment by jk1895** [comment]
I observed this too. No server, just single player in Modern Skyblock 3.
I wanted to craft 64 charged certus quartz. I put 64 certus quartz and 4x 64 redstone in my contraption. I get only 8 charged quartzs and 56 certus quarts. The radstone is gone... forever... :)
http://abload.de/image.php?img=2018-05-16_21.48.419aqoz.png

**Comment by Bartz24** [comment]
@thelapisfox I just tested your exact setup in my dev environment. There have been some changes to the code, so it may be fixed.

I'll leave this issue open and if issues continue, I'll have to look into it again

**Comment by xob** [comment]
I just experienced this problem in Modern Skyblock 3, with Sky Resources 2.3.8 with the same setup as the first report:
Quick dropper
Combustion collector
smart combustion controller
Manyullyn Casing with Electrum Combustion Heater fed with RF.

When making glowstone (4 redstone + 2 blaze powder = 5 glowstone), I put 2 stacks of redstone and a stack of blaze powder, and got only one successful recipe done, and then all that was left in the combustion "chamber" was the remaining blaze powder.

Quitting the world and opening it again (without reloading the pack) fixed the problem.
