### ISSUE TITLE
Things To Do/Fix/Add

### ISSUE THREAD

**Issue by Bartz24** [Bartz24/SkyResources#20]
Nothing for now

**Comment by ghost** [comment]
Cross compatibility for Ex Nihilo Adscensio 1.10.2 configs? Pls? (OwO)? I really need that, and it helps pack devs migrating their skyblock packs to 1.11.2 as Adscensio seems dead.

**Comment by Bartz24** [comment]
Nope sorry...the mods are too different for migration, and the 1.11.2 version of the mod is unsupported

**Comment by Skinklizzard** [comment]
hi not sure if you've planned for it yet or not, but the bee attractor code hasn't really changed in which case
you might want to add a check for drops.size() being zero otherwise it'll crash servers in biomes without valid bees when you call world.rand.nextInt(drops.size()), like the nether without magic/extra bees.

**Comment by SDUBZ** [comment]
it seems like i cant get any of the combustion heaters to do anything in sky resources 2 using version(2.0.18)

**Comment by Bartz24** [comment]
@SDUBZ did you place down a casing first? the combustion heater goes in the casing. a lot changed in Sky Resources 2. Reading the new and improved guide is highly recommended :D

**Comment by SDUBZ** [comment]
yes i did and tried wood,stone,iron,steel,dark matter and they didnt seem to do anything

**Comment by Bartz24** [comment]
well...i dont know what you're doing wrong, especially when you've used sky resources before
